# Handler to use from the handlers/ directory. If does it does not exist, will fall back to Breeze's internal default handler.
handler: "default_handler.py"

# Whether to disable chat functionality if an extension fails to load. This is great for security
disable_chat_on_extension_load_error: false
# NOTE: DOES NOT WORK YET

# Whether to disable chat functionality if the message handler raises an error. By default, Breeze will fall back to its internal default handler if a custom handler fails.
fully_cancel_message_on_handler_error: false
# NOTE: DOES NOT WORK YET

# DO NOT TOUCH THE FOLLOWING!!
config_version: "1.0"